# Generated by Django 3.1 on 2020-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_draw_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='draw',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
