# Generated by Django 3.1 on 2020-10-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201011_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquecode',
            name='code',
            field=models.CharField(blank=True, default='Automatic', editable=False, max_length=8, null=True, unique=True),
        ),
    ]
