# Generated by Django 3.1 on 2020-10-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201011_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquecode',
            name='code',
            field=models.CharField(blank=True, default='Automatic Generated', editable=False, max_length=8, null=True, unique=True),
        ),
    ]
