# Generated by Django 3.1 on 2020-10-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_draw_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='prizeId',
            field=models.IntegerField(default=0),
        ),
    ]
