# Generated by Django 3.1 on 2020-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
