# Generated by Django 3.1 on 2020-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201013_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquecode',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
