# Generated by Django 3.1 on 2020-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201013_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='label',
            field=models.CharField(max_length=12),
        ),
    ]
