# Generated by Django 3.1 on 2020-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_prize_try_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='retry_used',
            field=models.BooleanField(default=False),
        ),
    ]
